pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000

development:
  <<: *pg
  database: apidae_jep_dev
  username: pglocal
  password: pglocal

test:
  <<: *pg
  database: apidae_jep_test
  username: pglocal
  password: pglocal


production:
  <<: *pg
  host: postgresql-jep.alwaysdata.net
  database:
  username:
  password:
