# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f9f5d15a451fb22cc7cfcbfaaa2916dc20c6e92d05b9bc1e3f82d8ae19e5f05b7b28bb036b0e462877a8aa3907e189f4b50c60e1d6fc5deb0dccbe92add6ef6

test:
  secret_key_base: a617173fb0164d20c31e2c1f696479e79bfaa1658f8bedd98988ce2e3ac1a8e4efca450034acb291c0060e415760be37044e5b39a58ae6c0d7680aed011f2f11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
